export default {
	musicResources: [
	{
		id:20001,
		name:"经济舱",
		src:'/static/mp3/jingjicang.mp3',
		singer:{
			name:"Kafe.Hu",
			synopsis:"中国新说唱2020 第十期"
		},
		musicImg:'/static/music/music1.jpg'
	},
	{
		id:20002,
		name:"他只是经过",
		src:'/static/mp3/jingguo.mp3',
		singer:{
			name:"h3R3",
			synopsis:"他只是经过"
		},
		musicImg:'/static/music/music2.jpg'
	},
	{
		id:20003,
		name:"我像一个傻瓜",
		src:'/static/mp3/Frowned-blueface.mp3',
		singer:{
			name:"河北吴孟达",
			synopsis:"我像一个傻瓜2020"
		},
		musicImg:'/static/music/music3.jpg'
	},
	{
		id:20004,
		name:"偏爱",
		src:'/static/mp3/pianai.mp3',
		singer:{
			name:"张芸京",
			synopsis:"偏爱2020"
		},
		musicImg:'/static/music/music4.jpg'
	},
	{
		id:20005,
		name:"所念皆星河",
		src:'/static/mp3/xinghe.mp3',
		singer:{
			name:"房东的猫",
			synopsis:"所念皆星河"
		},
		musicImg:'/static/music/music5.jpg'
	},
	{
		id:20006,
		name:"山楂树之恋",
		src:'/static/mp3/shanzha.mp3',
		singer:{
			name:"程佳佳",
			synopsis:"山楂树之恋"
		},
		musicImg:'/static/music/music6.jpg'
	},
	]
}